kind: pipeline
name: default

workspace:
  base: /tmp
  path: "."

steps:
- name: Build image and push
  image: plugins/docker
  settings:
    repo: mellena1/software-engineering-blog
    autotag: true
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
