kind: pipeline
name: default

workspace:
  base: /tmp
  path: "."

steps:
- name: Build-image-and-push
  image: plugins/docker
  settings:
    repo: mellena1/software-engineering-blog
    autotag: true
    username:
      from_secret: username
    password:
      from_secret: password
